version: "3.8"
services:
  user_service:
    build:
      context: ./services/user_service
    ports:
      - "8000:8000"
    container_name: user_service

  discount_by_age_service:
    build:
      context: ./services/discount_by_age_service
    ports:
      - "8001:8000"
    container_name: discount_by_age_service

  discount_by_city_service:
    build:
      context: ./services/discount_by_city_service
    ports:
      - "8002:8000"
    container_name: discount_by_city_service
