[tool.poetry]
name = "postgresql"
version = "0.1.0"
description = "postgresql server inf"
authors = ["Sergii Pogorielov"]
license = ""

packages = []

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
